---
title: "Reading Notes"
author: "Moritz Twente"
date: last-modified
date-format: long
bibliography: nordatlantisk-ft.bib
csl: apa-cv.csl
suppress-bibliography: true
link-citations: false
citations-hover: false
lang: en
output-file: notes.pdf
format: 
  pdf: 
    documentclass: article
    mainfont: Jost
    filters: [quotation-marks.lua]
    quot-lang: de-CH
    colorlinks: true
    toc: true
    geometry:
      - top=22mm
      - bottom=18mm
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{} % clear all header and footer fields

        % first page footer
        \fancypagestyle{plain}{
        \fancyhf{}
        \fancyfoot[L]{\footnotesize Moritz Twente, 19-911-940, moritz.twente@unibas.ch}
        \fancyfoot[R]{\footnotesize \thepage}
        \renewcommand{\headrulewidth}{0pt}
        }

        % Right-justified header (smaller font)
        \fancyfoot[L]{\footnotesize Moritz Twente, 19-911-940, moritz.twente@unibas.ch}

        % Page number in footer (centered)
        \fancyfoot[R]{\footnotesize \thepage}

        % Remove header line (optional, cleaner look)
        \renewcommand{\headrulewidth}{0pt}

        % reduce whitespace below header
        \setlength{\headsep}{9pt}
---

# Folketing/Rigsfællesskabet

- @ackrenExploringRoleRegional2019
  + "National politics does not trigger islanders to the ballot box in the same manner as in the rest of Denmark and Finland. The difference is large, with some occasional exceptions when the difference is less than ten percent. Generally, the gap is 20 or more than 30 percent." [21]
  + "Representation in core state parliaments has never been a main issue for the self-ruled regions. The lack of conflict between the core state governments and the regional governments on how seats are distributed in national parliaments indicates its low importance in enhancing regional aims." [22]
  + "There is no formal hindrance that an incumbent elected from the islands could be included in national cabinet, yet it has not happened. A silent agreement keeps them out as it could give too much advantage to the self-ruled regions, which is not in line with a unitary state. Fears have been raised in Denmark that the four incumbents from the two self-ruled regions could utilize their mandate if the two-party blocks in parliament are of equal strength." [24]
  + "The unitary core states of Denmark and Finland systematically exclude their self-ruled regions from the national nucleus of government." [24]
  + "Legislatures from the Faroe Islands and Greenland have the role of distinct ethnic regional parties in the Danish Folketing. They form a parliamentary party of their own, usually representing the two largest parties from the two regions separately. The one-member parliamentary parties are members of the Faroe Islands committee and the Greenland committee respectively, together with 27 other members representing the core state parties in the Danish Folketing." [25]
- @cleggParliamentaryRepresentationOverseas2022
  + "But there are areas of policy in which the Faroes and Greenland cannot decide independently. These are foreign, defence and security policy, the constitution, citizenship, and currency, as well as the high courts. Additionally, there are some policy areas in which the Faroes and Greenland have not yet assumed control, most notably the police, judiciary, prison and probation services, aviation, and regulation of the financial sector." [235]
  + "Nevertheless, as we demonstrate below, in times of less rmly constituted parliamentary majorities, one or two of the North Atlantic members may play a key role in determining the political majority in the parliament. However, though Denmark has a strong tradition for minority coalition governments, the most common parliamentary situation is one in which none of these four members is important for the building of a parliamentary majority, and the subsequent making of policy. This way, although there have been times in which the Faroese and Greenlandic members become politically important and though they may be invited to participate in negotiations of special interest to their constituency, their general importance is probably best understood in terms of their symbolic presence and in their ability to articulate viewpoints and pass on knowledge of the northern parts of the Realm within the epicentre of Danish politics." [237]"
  + "Thus, moving to the question of whom these members represent, there is no question that they represent the people living in their geographical constituency, their home countries. However, a question of some disagreement among the current Greenlandic parliamentary members, in particular, is whether they are also expected to represent Greenlanders who live in Denmark. While Greenlandic and Faroese members have previously acted on behalf of their fellow citizens living in Denmark (e.g. via the asking of parliamentary questions), the current member of the Greenlandic Social Democratic Party believes that their representation should only be the concern of those MPs who represent the Danish district in which they live (interview with MP, Aki-Matilda Høegh-Dam, October 30, 2019)." [238]
  + "... it is custom in Danish legislative studies to use parliamentarians’ membership of legislative committees as an indicator of their political activities" [238]"
  + "An issue that has occasionally caused political debate is the question of whether the Greenlandic and Faroese MPs are only to concern themselves with questions related to their territories, and therefore staying out of mainland Danish political debates. According to the Danish Constitution, there is no doubt that these members may engage in any issue they wish. When governments have clear majorities North Atlantic members can vote on mainland Danish issues with no political consequence and attracting little notice, but when the parliament is more evenly split their votes can cause controversy. For example, in 2007, two Greenlandic members announced that they would vote with the opposition to allow asylum seekers with children not to be placed in detention centres, and this threatened the government’s majority. Hence, although Greenlandic members had previously voted on such issues without causing any concern, their vote at this point became an issue of much-heated debate. The spokesperson of one government party characterised their threat as 'two Greenlandic politicians have suddenly decided to come down from the ice and interfere in Danish politics' (Sjølie, 2008), while the vice-chairman of the Danish People’s Party announced that such behaviour would not go unpunished in the forthcoming negotiations on the future independence of Greenland (Henriksen, 2008). Not surprisingly, the post-colonial remarks, as well as the threat of sanctions, were interpreted in wider, symbolic ways, and heightened tensions between Greenland and the metropole. Eventually, a political majority behind the government was established and so the Greenlandic vote did not turn out to be decisive." [239]
  + "There are examples, particularly in relation to Greenland, when relations have soured if the MPs indicate a different view or set of interests to the metropolitan consensus and this certainly has the potential to harm relations." [248]
- @green-pedersenPartySystemOpen2020
  + not mentioning GL/FO parties at all when talking about DK party system
- @harderFaeroskeOgGronlandske2022
  + "Debatten er i særlig grad opstået i forbindelse med situationer, hvor det har været sandsynligt, at mandaterne kunne afgøre det parlamentariske flertal." [5]
  + "På trods af at Folketinget har dannet scene for denne forhandling de seneste godt og vel 70 år, ved vi kun meget lidt om, hvordan repræsentanterne fra Grønland og Færøerne agerer i Folketinget." [5]
  + "Med sit fokus på den nordatlantiske repræsentation i Folketinget udgør artiklen her et første systematisk forsøg på at afdække et empirisk hul i rigsfællesskabets historie." [6]
  + "Ifølge Skjæveland, der undersøger perioden 1953-1998, har den generelle opfattelse af disse mandater været, at de ikke blander sig i (syd)dansk politik, omend der samtidig hersker en opfattelse af, at de i stigende grad er blevet involveret heri." [7]
  + "Skjævelands undersøgelse viser således, at de nordatlantiske medlemmer er blevet involveret i regeringsdannelser hver eneste gang, dette var bare en smule nødvendigt. Særligt vigtige var de i 1971 og 1998 (Skjæveland, 2003: 122)." [7]
  + "I dag har Færøerne overtaget langt størstedelen af de mulige sagsområder på nær retsvæsenet, politiet, kriminalforsorgen, ud- lændingeområdet og grænsekontrollen samt områderne vedrørende den finansielle sektor og luftfartsområdet (Statsministeriet, 2020)." [8]
  + "Fordi flere af de nordatlantiske medlemmer holder længere orlov fra Folketinget, er data herfor indhentet på parti- og ikke individniveau." [9]
  + "Umiddelbart ser hverken det forhold, at et nordatlantisk medlem er fra et parti, der har rege- [SEITENUMBRUCH] ringsmagten hjemme, eller er fra en partifamilie, der har regeringsmagten i Danmark, ud til at påvirke medlemmets spørgeaktivitet signifikant (regeringsmagt hjemme: t-test, uens varians, P = 0,23; regeringsmagt i Danmark: t-test, uens varians, P = 0,83)." [10-11]
  + "I tråd med den tidligere litteraturs konklusioner viser den kvantitative indholdsanalyse af de parlamentariske spørgsmål, at de nordatlantiske mandater i perioden 2005-2019 hovedsageligt stiller spørgsmål af specifik relevans for Færøerne eller Grønland." [13]
  + kategorisering af spøgsmål: 1. Udenrigs-/forsvarspolitik, 2. overordn. forhold, Rigsfællesskabet, 3. ikke-hjemtagne områder, 4. færinger/grønlændere i DK, 5. øvrigt [13]
  + "en større andel af både de færøske og grønlandske spørgsmål angår enten færinger eller grønlænderes forhold i Danmark eller oplysning om Færøerne eller Grønland i Danmark." [15]
  + "Generelt kan det således konkluderes, at de nordatlantiske mandater overordnet set har anvendt Folketingets spørgefunktion til at få information om specifikke forhold og indgå i kritisk dialog om specifikke problemstillinger, snarere end til at føre diskussioner om det overordnede eller fremtidige forhold mellem medlemmerne af rigsfællesskabet." [15]
  + "For så vidt angår den måde, hvorpå de nordatlantiske mandater i perioden 1998-2019 er indgået i de parlamentariske flertal, er den umiddelbare konklusion meget lig den, som Skjæveland finder for perioden 1953-1998: Når man har kunnet, har man påvirket tingenes tilstand. Desuden har man – ikke overraskende – overordnet set støttet regeringer, hvis partifarve man har delt." [18]
  + "Efter valgene i 2011 og særligt i 2007 og 2015 var de nordatlantiske medlemmer imidlertid mere betydningsfulde for dannelsen af det parlamentariske flertal." [19]
  + "Overordnet set kan det fastslås, at de grønlandske medlemmer nu som før deltager langt mere aktivt i folketingsarbejdet, end de færøske medlemmer gør" [19]
  + "En yderligere lighed er, at både færøske og grønlandske medlemmer hovedsageligt engagerer sig i de sagsområder, der berører hjemlandet direkte." [20]
  + "På samme måde har man forholdt sig forholdsvis ens til dannelsen af parlamentariske flertal: Nordatlantiske medlemmer har generelt 'spillet deres parlamentariske chance', når den er opstået." [20]
- @harderSupplerendeMaterialeFaeroske2022
  + MFer liste op til inkl. 2015, også udvalgsmedlemskab
- @skaale20sporgsmalUS182021
  + "vi nordatlantere, som ordningen er, kan komme flyvende syd over Atlanten"
- @billeGronlandskeFolketingsmedlemmer2025
  + "Der har gennem årene været skiftende praksis, både med hensyn til om de grønlandske repræsentanter helt tilslutter sig en af de danske partiers folketingsgrupper, og hvorvidt de deltager i afstemningen om "rent indre danske" anliggender. Når valgresultatet er endt tæt mellem de politiske blokke, har grønlandske folketingsmedlemmer indimellem været afgørende for, hvem der kunne danne regering."
- @billeFaeroskeFolketingsmedlemmer2025
  + "Det har vekslet ved hvert folketingsvalg, hvilke to af de fire store partier på Færøerne, som opnår mandaterne."
- @gadGronlandskeFolketingsmedlemmer2022
  + "Siumut har stort set haft det ene af de grønlandske mandater siden partiets oprettelse i 1977. Det andet havde Atassut indtil 2001, hvor IA overtog det."
  + "Som folketingsmedlemmer har grønlandske politikere også haft mulighed for at påvirke dansk politik, ikke mindst i de tilfælde, hvor de har været afgørende for at bygge et parlamentarisk flertal: Efter valget i 1971 var Moses Olsen og Knud Hertling med til at sikre den socialdemokratiske regering. I 2007 så det en overgang ud til, at de grønlandske medlemmer kunne blive afgørende for, at den borgerlige regering kom i mindretal i en sag om asylfamiliers mulighed for at bo uden for asylcentre. I sådanne situationer har rimeligheden af, at grønlandske mandater tælles med på lige fod, været anfægtet."
- @harderArcticIndigenousRepresentation2024
  + "Since the focus of Arctic Indigenous peoples’ political mobilisation has not been the national parliaments, the literature has not been much concerned with national parliaments as arenas of Indigenous politics" [130]
  + "In the election for the Danish parliament, the Greenlandic people currently vote as one large constituency, and the amount of citizens that a Greenlandic representative represents is approximately equal to the number of citizens that a Danish representative represents on average [Clegg et al., 10--11]" [135]
  + "In the Nordic countries, there is no tradition of grouping people – nor elected officials – into their ethnicity or indigeneity. Therefore, there are no official statistics on the number of Indigenous MPs in the four Nordic, national parliaments. Yet, due to the demographic characteristics of Greenland, the two MPs elected by Greenland to the Danish parliament (with 179 seats) are generally Inuits. In turn, Danish constituencies have occasionally elected Inuits who live in Denmark to represent them, yet there is no statistical information on this." [137]
  + "In posing these questions the Greenlandic MPs carry out what Mansbridge terms surrogate representation, that is, representing people who do not live in the district of the representative." [139], referring to Harder 2022
  + "However, in the Danish parliament, the Greenlandic MPs may occasionally find themselves in situations where Danish representatives do not think it is appropriate that they interfere in so-called ‘Danish’ political matters. Hence, in situations where the actions of one or both of the Greenlandic representatives may influence the construction of the majority within the chamber, Greenlandic representatives have been bullied by representatives from Danish parties, who have publicly stated that due to the circumstance that Greenland has a large degree of self-government, the Greenlandic representatives ought to keep out of so-called 'Danish politics'." [141], referring to Clegg et al. 2022
  + "An interesting difference between the struggles that Indigenous representatives in the Danish and Canadian parliaments meet is that where the Canadian Indigenous representatives are self-regulating that they are not acting too much for Indigenous peoples only (because this may hurt their chances of re-election), Danish representatives are sometimes harassed for interfering in issues that are not of importance to Greenlanders only." [143]

# Folketing/Danish Politics in General

- @arndtFolketingswahlDanemarkVom2019
  + erwähnt nordatl. Mandate nur in Fussnote, Artikel zur Wahl 2015 auch nicht trotz Knappheit (?)
  + "Der von den Sozialdemokraten angeführte rote Block erreichte auch ohne die Partei Alternative und nordatlantische Mandate 91 Sitze, so dass eine Regierung erstmals nach 2007 wieder eine deutlichere Mehrheit von mehr als 90 Sitzen ohne Einberechnung der nordatlantischen Mandate hat" [785]
- @arterNordicParliamentsMuchofamuchness2016
  + "All the Nordic parliaments can be considered ‘working parliaments’ in that the significant policy deliberations take place outside plenary sessions, which are mostly poorly attended" [214]
- @christensenFolketingsvalgSiden19392022
  + Artikel zu den einzelnen Wahlen zeigen Ergebnisse ohne GL/FO
- @christiansenPolarizationLegislativeParty2021
  + "In Denmark, most bills originate from the government. The oppositions prefer to suggest ‘decisions’ (cf. Christiansen, 2018). Furthermore, most government bills pass, and the government rarely finds itself on the losing side in a vote." [749]
  + calculating disagreement with government parties per period [752] -> apply for GL/FO parties!
- @green-pedersenDetRadikaleVenstres2003
  + looking at political parties with a lot of influence on gvt formation: it's rather Radikale Venstre, no mention of GL/FO 
- @green-pedersenBlokpolitikOgNye2020
  + berücksichtigt GL/FO gar nicht, "Folketingsvalget i 2019 gav plads til ti partier" [311] > zählt nicht GL/FO mit
  + "Samarbejdsmønstrene kan belyses på forskellige måder, men en central tilgang, som denne artikel følger, er at se på, hvem der stemmer sammen med hvem i Folketinget." [312]
  + "Lægger man disse forskellige analyser sammen, er konklusionen, at rød og blå blok, og den endimensionelle opfattelse der ligger i disse begreber, er konstituerende for samarbejdet i Folketinget." [312]
  + "Som regel (jf. Green-Pedersen og Thomsen, 2005; Christiansen og Skjæveland, 2016; Kurrild-Klitgaard, Klemmensen og Hansen, 2006) studeres spørgsmålet ved 3. behandling af lovforslag, hvilket også er gjort nedenfor." [315]
  + "Sagt på en anden måde, så skal man i tolkningen af tabel 1 inddrage, at regeringen stort set kun fremsætter lovforslag, den ved kan vedtages. Tabellen siger ikke noget om politiske initiativer fra regeringen, der ikke bliver til noget." [316]
- @green-pedersenBlocPoliticsVs2005
  + "whichever bloc in the Danish parliament gains government power depends on who controls or gets the support of the median legislator, which is often [SEITENUMBRUCH] controlled by the small centre parties." [155/156]
  + "The unit of analysis is what we label ‘government periods’. By a government period, we mean a coherent period of years with the same government. [...] [SEITENUMBRUCH] The reason why sessions of the Danish parliament have not been chosen as a unit for analysis is the autocorrelation problem that this would create in the statistical analyses." [159/160]
  + "For instance, government formation in Denmark can almost always be explained using the same median legislator model, but the analysis of this article shows that the functioning of the parliamentary system nevertheless varies considerably depending on the internal cohesion of the party blocs which determines the possibilities of actually pursuing bloc politics after the government formation process." [166]
- @hansenCommitteeAssignmentPolitics2010
  + "The members from Greenland and the Faroe Islands are not included in the analysis." [391]
  + "The Danish committees are very influential and wield considerable power in the Danish parliamentary system (Damgaard 1990)." [384]
  + "Despite the fact that the committees of the Danish parliament are important for the policy process and there is evidence that the parties use them actively to influence policy." [382]
- @klintDanishLegislatorsDatabase2023
  + excluding GL/FO legislators, mentioning in parentheses
- @kurrild-klitgaardElectionInversionsCoalitions2013
  + "The Federal Paradox is harder to detect in the real world given that the political parties running in Greenland and on the Faroe Islands are not [SEITENUMBRUCH] identical to one another, and neither are they formally identical to the parties standing for elections in ‘continental’ Denmark – not to mention that parties did not run in elections before 1977, only individual candidates did. For that reason, judgments need to be made as to what parliamentary coalitions the four North Atlantic seats would likely caucus or collaborate with. Similarly, it has often been stated by the parties of Greenland and the Faroe Islands that they do not want to interfere in ‘domestic’ Danish politics and usually claim to not to seek to be kingmakers. Indeed, until the 1960s, the North Atlantic MPs usually did not intervene to save the lives of the Danish governments with which they otherwise sympathized (Skjæveland 2003, 114–24)."[129/130]
  + 1971 election inversion: "However, an election inversion took place relative to how the ‘continental’ Danes had cast their votes: Mr Krag could eventually form a government because he obtained support from both MPs from Greenland (with one of them being made a cabinet minister) and one of the two MPs from the Faroe Islands. That gave Krag a government with 90 of the 179 MPs supporting him (Skjæveland 2003, 116ff). In other words, a majority of the ‘continental’ Danish voters voted for a centre-right government but ended up with a Social Democrat government." [131]
- @nannestadPolitischeSystemDanemarks2009
  + "Bei vielen Gesetzentwürfen der Regierung ist die Mehrheitsbeschaffung unproblematisch, da sie unstrittig sind und von (fast) allen Fraktionen unterstützt werden." [84], Anteil von der Regierung eingebrachter Vorschläge seit 1984 nicht <70% (bis 2000) [82]
  + GL/FO wird erwähnt, aber in Erläuterungen im Wesentlichen nicht enthalten
- @skjaevelandGovernmentFormationDenmark2003
  + demonstrates importance of the median voter for gvt formation
  + book itself not accessible in Basel
- @skjaevelandModellingGovernmentFormation2009
  + "Danish expert observers generally agree that Danish government formation is largely a one-dimensional phenomenon, and thus great power is attributed to the median party, that is, the party that comprises the median legislator in parliament." [715]
  + "However, the [SEITENUMBRUCH] Danish parties are not the only relevant actors in relation to Danish government formation." [722-723]
  + "the more important their votes, the more involved they have become. They were most important in 1971 and in 1998 when their votes could decide who would be able to form the government. In both cases they clearly stated their preferences and in both cases they did so fully in accordance with their basic political orientation." [723]
- @kjaerDanskeFolketingsmedlemmerParlamentarisk2004
  + "Siden 1849 har der siddet et medlem valgt på Færøerne, fra 1947 forhøjet til to medlemmer, i det danske folketing, og fra 1953 har der ligeledes siddet to medlemmer valgt på Grønland. For disse nordatlantiske mandater gælder det, at de på mange måder er forskellige fra de resterende medlemmer af Folketinget i relation til deres rekrutteringsveje, og det er derfor valgt at udelade dem af analysen. Eksempelvis eksisterer der på Færøerne og i Grønland et andet partisystem, den fysiske afstand mellem kredsen og Folketinget er betragtelig større osv." > nicht inkludiert [32]
- @christiansenMinorityCoalitionGovernance2014
  + not mentioning GL/FO at all
- @skjaevelandMindretalsregeringerDanmarkFor2003
  + "... den socialdemokratisk-radikale regering, der blev dannet i 1960 af Kampmann og videreført af Jens Otto Krag. Socialdemokratiet og Det Radikale Venstre kontrollerede kun til sammen 88 mandater. Ved at gøre Mikael Gam, der var valgt i Grønland, til grønlandsminister sikrede regeringen sig imidlertid et ekstra mandat." [448]
  + "Selv om regeringen formelt var en mindretalsregering, giver det mening at overveje, om der reelt var tale om en flertalsregering. Forklaringen herpå skal findes i den anden af de to grønlandske repræsentanter, Nikolaj Rosing, og den skal findes i Slesvigsk Partis repræsentant, Hans Schmidt (se også Skjæveland, 2003: 114-124). Hvis den ene af disse reelt var medlem af regeringen, havde den et flertal. Alternativt havde den også et flertal, hvis de begge holdt sig neutrale i forhold til dansk politik, således at Folketinget kunne siges kun at bestå af 177 'relevante' mandater". [448]
- @skjaevelandPartyCohesionDanish2001
  + "Party cohesion in Denmark is high. Denmark is among those liberal democracies that have the highest degree of party cohesion." [35]
  + "Furthermore, all Danish divisions are registered and as Ozbudun observes in his classic comparative work, this tends to push up party cohesion figures." [36]
  + "Including all final votes on bills as well as the [SEITENUMBRUCH] two Danish types of resolutions" [39/40] (in contrast to Green-Pedersen/Thomsen 2005)
  + specifically excludes GL/FO "northatlantic matters" as 'local issues' [49]
- @westPoliticalPartiesParliamentary2025
  + "The literature often focuses on parliamentary questions as the most relevant tool for oversight activity (Wiberg, 1994)." [967]
  + removes FO/GL (and Aaland) from dataset [974 n. 5]
- @thuerkFlexibelStabilUnd2023
  + "In Dänemark variieren legislative Koalitionen stärker. Ein zentrales Instrument für die Mehrheitsbildung sind hier legislative policy-Abkommen, sogenannte forlig. Diese schriftlichen und öffentlichen Abkommen werden zwischen Regierungs- und Oppositionsparteien für die Dauer einer Legislaturperiode (oder gar länger) abgeschlossen und konzentrieren sich jeweils auf einen bestimmten Politikbereich, z. B. auf eine Rentenreform oder ein Migrationsabkommen. So können verschiedene par- teiliche Koalitionen ein stabiles Regieren ermöglichen." [305]
  + "Ähnlich argumentieren Kefford and Weeks (2020) ihrer Analyse Irlands und Australiens: in beiden Fällen haben sich Minderheitsregierungen ihre Zusammenarbeit mit parteilosen Abgeordneten „erkauft“, indem diese von policy-Zugeständnissen für ihre Wahlkreise profitiert haben. Anghel und Thürk (2021) zeigen, dass in Rumänien eine ethnisch basierte Spielart dieser Strategie auftritt: ethnische Minderheitsparteien verhandeln Zugeständnisse für ihre Gruppe und unterstützen im Gegenzug die nationale Minderheitsregierung." [306]
- ~~@damgaardPoliticalRolesDanish1997~~
- @valenGeographyPoliticalRepresentation2000
  + "Our research problem involves a focus on the contrast between central and peripheral areas within the Nordic countries. [...] For Denmark and Sweden, the concept of a periphery is scarcely recognized. [table with Center: 'The capital with surrounding areas', In-between: 'The islands', Periphery: 'Jutland']" [113]
- @ejnarhansenReconsideringPartyDistances2008
  + "However, in many of the West European parliaments, including Denmark, party discipline is very tight. Thus analysing individual legislator behaviour is of little use, and in such cases we should shift our focus to the parliamentary party groups and use these as the actors to be analysed." [266]
  + "The data excludes the representatives for Greenland and the Faroe Islands, since it is often unclear when they voted on a bill and what they voted." [277 Fn. 29]
- @pedersenPartyDistancesDanish1971
  + no mention of GL/FO
- @millerFriendsRivals1996
  + "[after 1957 election] There were four 'non-political' members -- two from Greenland, one [sic] from the Faroes, and the M.F. of the Slesvig party, representing the German minority." [71]
  + "The putative Social Democratic-Radical coalition had 84 of the 175 'political' seats in the Folketing, four short of a bare majority." [72]
  + "On March 1, 1960, the Folketing approved the EFTA Treaty, with the Government parties, the Conservatives, Aksel Larsen, and Thorkil Kristensen voting in favor, the Communists and the Slesvig party voting against, and the Liberals, one Conservative, and the two Greenlanders abstaining." [79]
  + "The retiring minister for Greenland, Kai Lindberg, a Social Democrat, recommended to Prime Minister Kampmann that he name as his successor a well-qualified Greenlander, Mikael Gam, a newly-elected member of the Folketing. Kampmann jumped at the idea and was in touch with Gam on the day after the election. Hitherto, the two Greenland M.F.s had been considered neutral or non-political, sitting in parliament to represent the interests of Greenland but avoiding controversial issues in Danish domestic politics. Gam saw in the offer of a cabinet post an opportunity to help his homeland and, after consulting with and gaining the approval of the other Greenland member, he agreed to accept it. This unexpected development gave the Social Democrats and Radicals the one vote they needed for a bare parliamentary majority of 89 seats. Though Gam -- who said he felt a little like 'a joker in a new card game' -- made no commitment to vote always with the Government, it was plain that as a minister, he would support the Government whenever necessary, especially since he would share in its cabinet decisions." [83]
- @hansenRealBorgenDanish2020
  + "In practice the actual number of votes in favour and against a bill is not important, as the passage or defeat is known in advance and the presence of members negotiated between the party whips." [3]
- @helboepedersenParliamentFOLKETINGETPowerful2020
  + "The Folketing provides particularly strong institutions for controlling the government and strong institutions for influencing decision-making but weak institutions for electing the government compared to many Western parliaments." [102]
  + only passing mention of GL/FO mandates
- @elklitElectoralSystemFair2020
  + "The two seats allocated to Greenland and the two allocated to the Faroe Islands are allocated separately, using d’Hondt in both cases. The consequence is that the two biggest parties in each of these two parts of the realm normally win a seat each." [64]

# Rigsfællesskabet in General

- @coatesIndigenousPeoplesArctic2020
- @coatesIntroductionCircumpolarDimensions2020
- @gadPostcolonialIdentityGreenland2009
- @gadGreenlandFaroeIslands2020
- @grydehojGovernmentPoliciesPriorities2020
- @hornPolitischeSystemDaenemarks2019
- @jacobsenDanmarksArktiskeUdenrigspolitik2021
- @jacobsenKalaallitPilluaritsiPerspektiver2019
- @jacobsenTemaredaktorensForordArktiske2021
- @naumIntroductionSituatingScandinavian2013
- @naumScandinavianColonialismRise2013
- @rahbek-clemmensenArcticGreatPower2016
- @rahbek-clemmensenArcticTurnHow2017
- @stephenInternationalePolitikUnd2018
- @westDanishRealmArctic2025
  + "The increasing international attention that Greenland and the Faroe Islands are receiving is opening the ‘black box’ of the Danish state and questioning the viability of the external dimension of the two sub-state units’ self-government systems." [589]
  + "... it is worth stressing that distinct elections select the North Atlantic MPs for the Folketing seats. This means that there is no institutional link between the North Atlantic parliamentarians in the Folketing and the national parliaments, and there is no institutional link between the North Atlantic parliamentarians in the Folketing and their respective national governments." [602]
  + "... Folketing allocates central Arctic-related parliamentary seats to North Atlantic MPs to legitimate the Arctic state position." [589]


# Political Parties in GL/FO

- @ackrenPoliticalPartiesGreenland2015
  + "During the 1984 election some of the parties had shifted their position in the left-right continuum. Siumut was now entering the centre in politics and the party had also shifted co-operation partner within the Danish parliament from the Social People's Party towards the Social Democrats. Atassut was also moving towards the centre or more right within politics and began co-operation with the Danish Left [sic] (Venstre)." [324]
  + "In 2002, a new party entered the scene in Greenland, Demokraatit, which is a social-liberal party more to the right on the left-right spectrum." [327]
  + "The political development in Greenland shows that the major political cleavages have been related to the relationships with Denmark and internal or domestic matters throughout the period of investigation. The major divisions in politics have been between status quo, home rule and increased self-government with full independence as the ultimate goal." [333]
- @ackrenExploringRoleRegional2019
  + "However, the overwhelming cleavage goes between separatism and unionism, which either unite or open rifts between people on the islands." [27]
- ~~@ahlnessNunattaQitornaiParty2020~~
- @michelsenGronlandPartisystemUdvikling1979
  + "Ved folketingsvalg var Grønland indtil valget 9. januar 1975 opdelt i to valgkredse med hver 1 mandat: en nord-  og østgrønlandsk kreds og en sydgrønlandsk kreds. Med valget i 1975 blev Grønland 1 kreds med 2 mandater." [52]
  + "De to grønlandske MFere deltager i lovgivningen, men det er kun sjældent, de har haft betydning for flertalsdannelsen, og i grønlandsspørgsmål er folketinget sjældent delt midt over, så grønlændernes stemmeafgivning får direkte betydning for Grønland. Endelig kan to mandater ikke få afgørende indflydelse på lovudformningen. I to tilfælde har grønlandsk valgte MFere opnået ministerposten, men her opstår let den fare at blive gidsel for andres politik." [55]
- ~~@westMPFirefightingWhen2018~~
- ~~@westFaeroskPolitikMellem2020~~
- ~~@westSkipanarligarFortreytirOg2022~~
- ~~@westLogtingidOgTingnevndirnar2025~~

# Voting Behavior/Power
- @felsenthalVotingPowerMeasurement2005
- @gelmanStandardVotingPower2004
- @hillerDistributionPowerGoverning2013
- @hugParliamentaryVoting2013
  + "VanDoren (1990), studying how legislative proposals are delat with by committees and which proposals are voted upon in roll call votes, notes that many never leave the committee stage." [141]
  + "Thus, it cannot surprise that two reviews of the literature on parliamentary votingput political parties [and not individual MPs] more or less at center stage. Collie (1984) argues that the literature has essentially focused on research questions dealing with the collective [...] or individuals." [140]
  + "As the data scholars can use is related both to the visibility and thus to the possibility of monitoring, some caution is advised when using information on parliamentary voting. [...] Thus, as in many quasi-experimental studies, we need to be wary about possible selection issues." [142]
  + three main areas of research dominating the field: "First, explaining votes in parliament, either specific ones or a whole set of votes, has been a main thread in the literature. A major preoccupation in this research area is to determine which of the (possibly many) principals influence the MPs' voting behavior. Second [...] research dealing with the cohesion of political parties and sometimes other groups has proved an active field. Finally, determining what conflict lines and cleavages characterize the work in parliament has preoccupied scholars to a considerable extent." [142]
  + "While Rice's (1925) index to measure cohesiveness still plays a central role, several scholars have proposed modifications and extensions. As Rice's (1925) index only considers the yes- and no-votes, some authors suggest that abstentions should also be considered. [...] Hix et al. (2006) propose an 'agreement index' that also considers the third option an MP may have when considering voting, namely to abstain. Their measure, however, will always yield positive values, contrary to Attina's (1990)."
  + "[...] the main problems in the study of parliamentary voting, namely that the latter are often only partially observable and subject to considerable agenda influences." [149]
  + "Related to this issue of partial observability is the more general question how votes in parliament have to be conceived in the larger context of parliamentary decision making. Londregan (2000b), for instance, shows that parliamentary voting is related ot the various previous stages leading up to a parliamentary decision." [150]
- @hugRollcallVotingBehaviour2020
  + "In addition, as [recorded roll call] behaviour is in most legislatures only a subset of all behaviours, and also is likely to be influenced by a myriad of factors, care is warranted when analysing such data." [146]
- @laneAnalysisVotingPower2007
- @leechPowerIndicesLarge2013
- @penroseElementaryStatisticsMajority1946
- @raunioControllingOutcomesVoting2002
- @vandeemenParadoxesVotingPower2003
- @weberThoughtsVotingPower2020
- @hugSelectionEffectsRoll2010
- @butikoferStrategicBehaviourParliament2015
- @hugPartyPressureEuropean2016
  + "I use here the term ‘roll call vote’ as synonymous with ‘open voting,’ i.e. voting methods where information on individual voting decisions is freely available to everyone." [214 Fn. 1]
- @baileyTwodimensionalAnalysisSeventy2018
- @fjelstulDecisionmakingUnitedNations2025
  + "Figure 7 summarizes the impact of these differences on a commonly used statistic, Signorino and Ritter ’s (1999) S-score that reflects the similarity between two countries’ voting records." [8] >>> METHOD, see Signorino/Ritter 1999
- ~~@lucasPoliticiansTheoriesVoting2025~~
- @comanDimensionsPoliticalConflict2017
  + using data from DK for comparative study
- @maiVotingPartyLine2023
- @maiDivisionLabourDissenting2024
- @carrubbaLegislativeVotingBehavior2008
- @louwerseReachingAisleExplaining2017
  + "We know that the distinction between opposition and government parties is crucial in explaining voting behaviour under parliamentary government." [746]
  + using coalition-opposition and government-opposition distinction to look at both support and cabinet party effects
- @pourebrahimiDyadicMethodInvestigate2025
  + using tables to display decision pairing
  + could be worth a look again for methods
- @hugParliamentaryVotingProcedures2015
 + open recorded votes are standard in Folketing already between 1970--1994 according to Saalfeld 1995: 541 [951-952]
- @siebererRollCallVotesGerman2020
  + "RCVs are one of the most important data sources on parliamentary behavior. Beyond producing legislative output, RCVs put the positions of Members of Parliament (MPs) and party groups on the public record, serve party leaders as an instrument with which to monitor backbench behavior, and enable opposition parties to obstruct parliamentary business." [1137]
- @cencigVotingBehaviourEuropean2017
  + "Furthermore, scholars showed that party groups, rather than nationality, have played a huge role in coalition formation in the EP from its very establishment." [4]
  + "However, when breaking down votes into more specific sub issues (such as justice or human rights), the author found the country of origin to become a better predictor in some cases, a result which is easily concealed by the pooled, large-n analyses which are standard in the literature." [5]
- ~~@wuestRollCallVotes2016~~
- @anghelInfluencePayOffsLegislative2021
  + "The results of our two-part empirical analysis indicate that ethno-regional parties try to achieve more group-specific policies and are less interested than mainstream parties in securing office positions or policy pay-offs on the traditional socioeconomic dimension. We observe that, through their strategy of offering legislative support, minorities benefited from a constant increase in funding and attention to their specific needs." [136]
- @signorinoTaubNotTaub1999

# Second-Order Parliaments
- for second order definition, see 10.1017/S000712349800026X

# Cross-Parliamentary Control

- @harderCrossparliamentaryControl2025
  + "I define cross-parliamentary control as parliamentary control in which representatives in one government system engage in control activities that control a government in another." [3]
  + "To the Greenlandic people, the Danish parliament constitutes a second-order parliament and, for this reason, the Danish Realm constitutes a suitable case to explore the yet unconceptualized notion of cross-parliamentary control." [3]
  + "Thus far, cross-parliamentary control as I define it here has only been observed by Jensen et al. (2013)." [5]
  + "Despite the formal equal participation of the Greenlandic representatives, voter participation in Greenland is higher at national elections than at the Folketing elections (Supplementary Figure A). Hence, in general, local voters seem to be more concerned with local politics than the politics, which is decided in and by the Realm, and from a Greenlandic perspective, the Danish Folketing appears as a second-order parliament." [8]
  + "From a Greenlandic perspective, as mentioned above, the Danish parliament is considered a second-order parliament. For this reason, it constitutes a particularly likely case for the yet unexplored concept of cross-parliamentary control. However, gaining more knowledge about the case is also important in its own right: In the current ‘Race to the North’ for exploitation of hydrocarbon and mineral wealth and access to cargo transport which increases as the ice melts, Greenland is an important actor." [9]
  + "This study contributes with new knowledge concerning the dynamics between the Greenlandic representation in the Danish parliament and the Greenlandic government." [9]
  + "The questions in the dataset were hand-coded through a two-step process. First, they were divided into questions that were posed while the representative’s party was in opposition at home (i.e. in Greenland) and questions that were posed while the representative’s party was in government. After this, questions were coded as either ‘involving oversight of government at home’ or ‘not involving oversight of government at home.’ Unless questions directly address the actions or inactions of the Greenlandic government, these were coded as ‘not involving oversight of government at home’." [9]
  + "they offer valuable insights into the case and Greenlandic representation in the Danish parliament, an area that has yet to be thoroughly researched (see, however, Harder, 2022)." [10]
  + "Of importance, almost all the questions that carry out cross-parliamentary control are posed by one of the two parties, Inuit Ataqatigiit (IA) (52 of the 56 questions). Hence, in the study, cross-parliamentary control seems to be a one-party phenomenon." [10]
  + "In addition, as I show below, being in opposition at home seems to be a general prerequisite for posing questions that control at home, and SIU spends considerably less time in opposition at home during the period." [11]
  + "Moving to the interesting question of government status, as anticipated, most of the questions that carry out cross-parliamentary control (52 of the 56) are posed by representatives that belong to opposition parties in Greenland (H3)." [11]
  + "Finally – and of importance for the theory building – all but one of the questions which carry out cross-parliamentary control were posed from 2011 and onwards. As I initially explained, from 2001–2011 the Greenlandic members of the Danish parliament belonged to the same North Atlantic [SEITENUMBRUCH] party group. Therefore, it seems that a prerequisite for cross-parliamentary control is that representatives find themselves in a relation of party competition within the parliament that questions are posed." [11-12]
  + "Hence, in the contexts that are of relevance here, representatives who belong to parties that compete at one government level (usually the more local one) may find themselves in a situation of cooperation at another level." [12]
  + formulated thesis based on observations: "Representatives will especially engage in cross-parliamentary control when they belong to parties that are in opposition within the government system where they seek to control the government." [12]
- @staehrharderCaseInnovativeParliamentary2022
  + "If applied this way, the Folketing could act as an alternative arena for control of the national periphery government, and we would be witnessing an example of what we term cross-parliamentary control."
  + "Thus far, this type of control in which representatives use the control tool of another country’s parliament to control their home government has not yet been an issue of much attention in the legislative literature."
  + "Corresponding to our expectations, our analyses show that most of the questions posed by the North Atlantic members of the Danish parliament, who are in opposition at home, concern the actions or inactions of the Danish government. Nevertheless, 7.8 pct. of these questions concern the actions or inactions of the members’ home government. Hence, they enact cross-parliamentary control."
  + "Moreover, in line with our initial expectations, which are based on the former findings of Harder and West (Harder 2021; West 2019), we find that Greenlandic MPs make use of this possibility to a much larger extent than the Faroese members do. However, contrary to our expectations, it is the members from the parties that are most critical towards the Danish Realm, which makes the most use of the opportunity to gain information on the actions of their home-governments from the Danish Authorities. Especially, this tendency is particularly strong for Faroese members. We believe this to be a sign that partisan motives at home are more important to North Atlantic politicians in the Danish parliament than we initially expected them to be."
- @jensenParliamentaryQuestionsOversight2013

# Parliamentary (Open) Data

- @benoitDataScienceMeets2025
  + "In recent years, legislative institutions across the world have experienced a 'transparency rush' that has led to the opening of large and extremely diversified deposits of data. This trend has been paralleled by easier access to these deposits due to their increasing digitalisation" [41]
- ~~@berntzenParliamentaryOpenData2019~~
- ~~@mahrOneTemplateRule2025a~~
- ~~@twenteNordatlantiskft2024~~
- @doringParlGov2024Release2024
  + provides basic info for FO/GL parties that were at least once elected to FT.
  + for elections, only seat numbers, not vote shares are provided for FO/GL parties
- ~~@folketingetFolketingetsAbneData2026~~
- @weissLatinAmericanLegislators2025
- @louwerseDutchParliamentaryBehaviour2018
  + "Comparative data availability does remain an issue, however. The step from parliamentary records to ready-to-use datasets requires some investment of time, resources and skills, and as a result comparative work is relatively scarce (but see Carey, 2007, 2008; Coman, 2016; Hix and Noury, 2016; Kam, 2009; Sieberer, 2006)." [150]
- ~~@sanchez-nielsenSuDaMaSustainableOpen2021~~

# Newspaper Reports

- @almerFolketingetVilDrofte2023
- @berthelsenFormandsopgorSiumutHoeghDam2023
- @buggeRegeringensIndenrigspolitiskeFlertal2023
- @djorupViVaelterIkke2012
- @frostLokkeRaserNordatlantiske2022
- @hviidVittusQujaukitsoqMelder2025
- @joensenLagtingsformandenVilAfskaffe2019
- @joensenNordatlantiskePartierVil2022
- @kamstrupNuHarVi2017
- @kristensenTolkemangelFolketingetFamiliemedlem2023
- @kuitseKunoFenckerOnsker2025
- @larsenSkatteministerTilNytarskur2017
- @lutzenForoyskuFolkatingsumbodiniElva2025
- @mansoAnalyseMinisterstormEndte2025
- @ritzauOmstridtGronlandskPolitiker2016
- @ritzauForvirringFolketingssalenAkiMatilda2023
- @ritzauFaeroskeFolketingsmedlemmerEfter2023
- @ritzauLokkeErMallos2023
- @ritzauKommentatorRegeringenKommer2023
- @schultz-lorentzenNordatlantenFaellesFront2011
- @skaaleFaeroskMFerNordatlantiske2022
- @skaaleUppspunnidPartapolitisktKrut2025
- @skouKaareFireMandater2008
- @sorensenEfterBrokBla2022
- @sorensenMedieAkiMatildaHoeghDam2023
- @svendsenDramaOmMistillid2025
- @synnestvedtSiumutVilBlande2021
- @turnowskySkatteministerBeklagerGronlaenderudtalelse2017
- @valentinFaeroskPolitikerNordatlantiske2025
- @valentinMedieTolkeFolketinget2025
- @veirumForskerNordatlantiskIndflydelse2022
- @veirumMarkusOlsenFolketinget2023
- @vollerGronlandskMFerVil2008
- @corfixenAkiMatildaHoeghDamEr2025
- @dallGronlandOgFaeroerne2022
- @djurhuusAajaStudlarStjornini2025
- @einarssonUndrastForoyskOg2025
- @frigaardSadanTaellerMan2022
- @friisTiArSiden2025
- @hansenTalePaGronlandsk2023
- @hansenSaraOlsvigStiller2013
- @hyldalSiumutpolitikersKlageEr2024
- @jacobsenLogdUndirBlanda2025
- @jenvallAkiMatildaHoeghDamHar2025
- @jenvallSprogstridFolketingetSplitter2024
- @jersildGronlandskProfilSmider2025
- @jorgensenStortFremmodeTil2025
- @kirkebaek-johanssonStemmeslugerForladerGronlandsk2025
- @klingeGronlandskFolketingssalenSplitter2024
- @lindstromAajaPegerPa2022
- @mollerAkiMatildaHoeghDamKlager2024
- @mollerDanskFinanslovsforslagMange2025
- @mollerAajaChemnitzMilliarder2025
- @nathanGronlandskMferSer2024
- @okkelsHvemSkalNu2025
- @pabstMetteFrederiksenReagerer2024
- @raatzDagensSidsteTaler2013
- @rasmussenGronlandsMFereGennem2022
- @raunwesthAkiMatildaHoeghDamSoger2025
- @raunwesthAkiMatildaHoeghDamsAfloser2025
- @ritzauFaeroskMandatVil2022
- @ritzauPaGronlandskLanger2023
- @ritzauGronlandsRegeringspartiTruer2024
- @ritzauAkiMatildaHoeghDamSoger2025
- @ritzauMarkusOlsenTakker2025
- @sermitsiaq.agLundOlsenErstatter2013
- @skaerbaekFolketingstolkeHarSagt2025
- @sommerNordatlantiskeMandaterKan2007
- @sorensenArEfterAkiMatilda2024
- @thiemannRodeFarDet2022
- @veirumPartilederePatalerGronlandsk2022
- @sjolieDanmarkManglerOpgor2008
  + ned fra indlandsisen-quote

# Other

- @hazanCentrePartiesPolarisation1997
- @nolanStrexExtraString2024
- @statsministerietValgdatoPaFaeroerne2022
- @straubingerResultsDanishGeneral2022
  + not including GL/FO mandates